CAR_REPAIR_Q:0.07
BIKE_REPAIR_Q:0.04
SCOOTER_REPAIR_Q:0.02
CAR_ICON:./src/org/unibl/etf/pj2/ePJ2/img/car.png
BICYCLE_ICON:./src/org/unibl/etf/pj2/ePJ2/img/transport.png
SCOOTER_ICON:./src/org/unibl/etf/pj2/ePJ2/img/electric-scooter.png
RECEIPTS_PATH:./src/org/unibl/etf/pj2/ePJ2/rental/receipts/
DISTANCE_NARROW:2
DISTANCE_WIDE:3
DISCOUNT:0.2
DISCOUNT_PROM:0.85
CAR_UNIT_PRICE:2000
BIKE_UNIT_PRICE:1000
SCOOTER_UNIT_PRICE:500
receiptsFolder:./src/org/unibl/etf/pj2/ePJ2/rental/receipts
rentals:./src/org/unibl/etf/pj2/ePJ2/helper/Iznajmljivanja.csv
vehicles:./src/org/unibl/etf/pj2/ePJ2/helper/Prevozna sredstva.csv
malfunctionCostsPath:./src/org/unibl/etf/pj2/ePJ2/stats/malfunctionCosts/